import 'dart:ui';

class WlsPosColor {
  static const Color butterscotch             = Color(0xfffaaf40);
  static const Color tomato                   = Color(0xffee4036);
  static const Color black_16                 = Color(0x29000000);
  static const Color cerise                   = Color(0xffec297b);
  static const Color darkish_purple           = Color(0xff9e1f63);
  static const Color white_five               = Color(0xffebebeb);
  static const Color warm_grey_three          = Color(0xff707070);
  static const Color white                    = Color(0xffffffff);
  static const Color white_two                = Color(0xffd2d2d2);
  static const Color pale_grey_three          = Color(0xfff7f7f9);
  static const Color darkish_purple_two       = Color(0xff9e1f63);
  static const Color black_four               = Color(0xff050505);
  static const Color orangey_red              = Color(0xfffc512e);
  static const Color butter_scotch            = Color(0xfffeab3a);
  static const Color black                    = Color(0xff000000);
  static const Color orangey_red_two          = Color(0xfffc512e);
  static const Color grid_line_color          = Color(0xffcdd6eb);
  static const Color brownish_grey_six        = Color(0xff676767);
  static const Color navy_blue                = Color(0xff000947);
  static const Color warm_grey_six            = Color(0xffa1a1a1);
  static const Color pale_lilac               = Color(0xffe1e7ff);
  static const Color pale_grey_four           = Color(0xfff0f0f1);
  static const Color tangerine                = Color(0xfff29200);
  static const Color marigold                 = Color(0xfffdc100);
  static const Color warm_grey_seven          = Color(0xff88867b);
  static const Color warm_grey_light          = Color(0x6c88867b);
  static const Color warm_grey                = Color(0x34b1b0b4);
  static const Color dark_grey                = Color(0x345B595B);
  static const Color light_grey               = Color(0xFFD8D8D8);
  static const Color grape_purple             = Color(0xff421728);
  static const Color grape_purple_two         = Color(0xff9a00c6);
  static const Color shamrock_green           = Color(0xff02bc4d);
  static const Color reddish_pink             = Color(0xffff2c57);
  static const Color icon_green               = Color(0xff00a884);
  static const Color app_blue                 = Color(0xff34A5C2);
  static const Color light_dark_white         = Color(0xfff1f1f1);
  static const Color white_six                = Color(0xffe8e8e8);
  static const Color marine                   = Color(0xff021d54);
  static const Color brownish_grey            = Color(0xff606060);
  static const Color cherry                   = Color(0xffd30e24);
  static const Color marine_two               = Color(0xff012161);
  static const Color pinkish_grey_two         = Color(0xffc1c1c1);
  static const Color white_six_new            = Color(0xfff5f5f5);
  static const Color warm_grey_new            = Color(0xff9e9e9e);
  static const Color yellow_orange_three      = Color(0xffffb700);
  static const Color dark_green               = Color(0xff0b9275);
  static const Color dark_red                 = Color(0xffd10b22);
  static const Color transparent              = Color(0x00ffffff);

  static const Color game_color_pink          = Color(0xfffba8d4);
  static const Color game_color_red           = Color(0xfff83424);
  static const Color game_color_orange        = Color(0xfff9b81c);
  static const Color game_color_brown         = Color(0xffc86e29);
  static const Color game_color_green         = Color(0xff8ac539);
  static const Color game_color_cyan          = Color(0xff6bd0ca);
  static const Color game_color_blue          = Color(0xff0588de);
  static const Color game_color_magenta       = Color(0xffd252f7);
  static const Color game_color_grey          = Color(0xff8b919c);
  static const Color game_color_black         = Color(0xff000000);
  static const Color ball_border_bg           = Color(0xffaaaaaa);
  static const Color ball_border_light_bg     = Color(0xfff5f5f5);
  static const Color neon_green               = Color(0xff39FF14);
  static const Color neon_yellow              = Color(0xfffff51a);
  static const Color red                      = Color(0xffFf073a);
  static const Color app_bg                   = Color(0xff001d57);
  static const Color border_inside            = Color(0xfff3f3f3);
  static const Color zoo_game_color_green     = Color(0xff54b25a);
  static const Color white_seven              = Color(0xffececec);
  static const Color periwinkle_blue          = Color(0xff97a3ff);
  static const Color golden_rod               = Color(0xfff5c819);
  static const Color warm_grey_four           = Color(0xff808080);
  static const Color warm_grey_eight          = Color(0xff777777);
  static const Color white_five_two           = Color(0xfff3f3f3);
  static const Color brownish_grey_seven      = Color(0xff5e5e5e);
  static const Color brownish_grey_two        = Color(0xff606060);
  static const Color greyish                  = Color(0xffa5a5a5);
  static const Color gray         = Color(0xff636364);
  static const Color dark_gray         = Color(0xff4f4f51);



}