class GetConfigResponse {
  int? responseCode;
  String? responseMessage;
  ResponseData? responseData;

  GetConfigResponse(
      {this.responseCode, this.responseMessage, this.responseData});

  GetConfigResponse.fromJson(Map<String, dynamic> json) {
    responseCode = json['responseCode'];
    responseMessage = json['responseMessage'];
    responseData = json['responseData'] != null
        ? new ResponseData.fromJson(json['responseData'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['responseCode'] = this.responseCode;
    data['responseMessage'] = this.responseMessage;
    if (this.responseData != null) {
      data['responseData'] = this.responseData!.toJson();
    }
    return data;
  }
}

class ResponseData {
  String? message;
  int? statusCode;
  List<Data>? data;

  ResponseData({this.message, this.statusCode, this.data});

  ResponseData.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    statusCode = json['statusCode'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['statusCode'] = this.statusCode;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String? oTPTYPE;
  String? cOUNTRYCODES;
  String? vERIFYPOSWITHOUTTERMINALMAPPING;
  String? rEPORTCHUNKSIZE;
  String? dEFAULTORGSTATUS;
  String? dIRECTRETAILERDEFAULTSETS;
  String? aSSIGNSCHEDULEDCOMMSET;
  String? mAILBOXPASSWORD;
  String? sYSTEMALLOWEDCHAINTYPECODE;
  String? lENGTHOFDECIMALPLACES;
  String? pLAYERKYCAPPROVALREQUIRED;
  String? dEFAULTDATEFORMAT;
  String? aLLOWLOGINFORBLOCKEDUSER;
  String? oTPLENGTH;
  String? eXTERNALCALLHEADERCREDENTIAL;
  String? rETAILPASSWORDREGEX;
  String? tOKENREGEX;
  String? pASSWORDVALIDITYCHECK;
  String? oRGCODELOGICID;
  String? uSERPERTXNLIMIT;
  String? nEGATIVEDISTRIBUTABLELIMITALLOWED;
  String? wINNINGTAXAPPLICABLE;
  String? dEFAULTTXNIP;
  String? aDDITIONALTRANSACTIONDATA;
  String? mINWINAMOUNTFORPARENTAPPROVAL;
  String? eXPIRYDURATIONFORWRONGPASSWORD;
  String? mAGTDEFAULTSETS;
  String? rETSUBUSERROLEID;
  String? aLLOWEDCHAINTYPE;
  String? mULTIPLEUSERINVENTORYACCESSORGTYPE;
  String? zIPCODEREGEX;
  String? bOUSERSYNCALLOWED;
  String? oLAGAMEID;
  String? cOUNTRYCODE;
  String? aPPDOWNLOADURL;
  String? aWSREGIONVALUE;
  String? cURRENCYID;
  String? cREDITLIMITDISPLAYONAPP;
  String? dATEFORMAT;
  String? uSERPERDAYTXNLIMIT;
  String? sUBUSERALLOWEDORGCODES;
  String? rESCHEDULEALLOWED;
  String? fAILEDLOGINATTEMPT;
  String? tHIRDPARTYUSERSEARCHALLOWED;
  String? sYSTEMID;
  String? oTPEXPIRY;
  String? tDSAPPLICABLE;
  String? pHONEREGEX;
  String? aWSACCESSKEYID;
  String? wEAVERADMINLOGIN;
  String? mOBILEREGEX;
  String? pLAYERTDSRATE;
  String? pLAYERTDSREQUIREDFORNOTAPPROVEDWINNING;
  String? aDVANCEDREGISTRATIONREQUESTSTEPS;
  String? dEFAULTBILLCONFIG;
  String? sHORTCLIENTNAME;
  String? dECIMALCHARACTER;
  String? pASSWORDVALIDITYDAYS;
  String? oRGBANKDETAILSREQUIRED;
  String? dISPLAYCURRENCYSYMBOL;
  String? dEFAULTRETAILERSUBUSERROLE;
  String? uSERDEVICEMAPPING;
  String? rEQUESTTIMESTAMPCHECK;
  String? sUBSCRIPTIONMSGCOLOR;
  String? iSB2BANDB2C;
  String? rMSSERVERURL;
  String? dISPLAYUSERBALANCE;
  String? dAILYTXNSUMMARYNUMBERS;
  String? cONTENTSERVERTYPE;
  String? nUMBERFORMATREQUIRED;
  String? tICKETSERVERIP;
  String? pLAYERREQUIREDFORNOTAPPROVEDWINNING;
  String? rEPORTMAILS;
  String? dEFAULTINVOICESTATUS;
  String? mINWINAMOUNTFORAPPROVAL;
  String? iPCHECKFORCLIENTTOKEN;
  String? aGTSUBUSERROLEID;
  String? bALANCECHECKFORPAYOUT;
  String? oRGCODEREQUIREDONREG;
  String? iSMAILMANDATORY;
  String? rEQUESTTIMEOUT;
  String? aLLOWLOGINFOREXTERNALUSER;
  String? mASTERWAREHOUSEID;
  String? aMOUNTLOCALEFORMATINGREQUIRED;
  String? rEGISTRATIONALLOWEDORGTYPE;
  String? uSERCHECKFORTERMINAL;
  String? tHIRDPARTYUSERUPDATEALLOWED;
  String? uSEMOBILEASUSERNAME;
  String? aWSSECRETACCESSKEY;
  String? dECIMALFORMATINGREQUIRED;
  String? rESOURCEDOWNLOADURL;
  String? rEGISTRATIONREQUESTEXPIRY;
  String? sEARCHLATESTRECORDFIRST;
  String? oRGBANKDETAILSMANDATORY;
  String? tERMINALLOCATIONDETAILS;
  String? aWSSENDERID;
  String? sUBSCRIPTIONMSG;
  String? sMSONPAYMENT;
  String? aLLOWEDWALLETMODE;
  String? lANGUAGECODE;
  String? mAXTXNVALUEALLOWED;
  String? cLIENTDOMAINNAME;
  String? eMAILUNIQUENESS;
  String? cOUNTRY;
  String? nETAMOUNTCHECK;
  String? cURRENCYLIST;
  String? sETTLEMENTBLOCKEDDURATION;
  String? aLERTNUMBERS;
  String? mULTIPLEWAREHOUSEALLOWED;
  String? bOSHUTDOWN;
  String? dEFAULTDOMAINID;
  String? oRGCODEREGEX;
  String? sENDIAMROLEMAIL;
  String? cLAUTOAPPROVALLIMIT;
  String? iSLSENABLED;
  String? oLANETCOLLECTIONCOMMALLOWED;
  String? aLLOWEDORGCODES;
  String? mOBILECODEMINMAXLENGTH;
  String? sYSTEMALLOWEDLANGUAGES;
  String? eNABLEORGPOSASSIGNMENTONREG;
  String? dUPLICATETXNTIMECHECK;
  String? sECONDARYDBSYNC;
  String? mAXCREDITLIMIT;
  String? tHIRDPARTYUSERREQUIRED;
  String? mAILBOXUSERNAME;
  String? uPDATEUSEREMAILWHENORGUPDATE;
  int? domainId;
  String? iPCHECKFORUSERTOKEN;
  String? tDSRATE;
  String? pASSWORDTYPE;
  String? mAXBULKPAYMENTALLOWED;
  String? eNABLEPAYINORGSEARCH;
  String? mAGTSUBUSERROLEID;
  String? bETGAMESID;
  String? lOWERTIERACCESSALLOWED;
  String? domainName;
  String? cLINETTOKENGENERATIONALLOWED;
  String? rEPORTDOWNLOADURL;
  String? iSBACKENDGRACEPERIOD;
  String? mOBILEUNIQUENESS;
  String? oRGTERMINATEDAYS;
  String? sENDIAMROLESMS;
  String? rOUNDOFFREQUIRED;
  String? cLIENTNAME;
  String? lOWERTIERUSERACCESSALLOWED;
  String? mAILBOXEMAILID;
  String? eMAILREGEX;
  String? cALLUSMESSAGE;
  String? aLLOWEDDECIMALSIZE;
  String? sCRIPTUSERID;
  String? pLAYERTDSREQUIREDFORAPPROVEDWINNING;
  String? lOGLOGINACTIVITY;
  String? iSORGMOVEMENT;
  String? dOMAINUSERROLEID;
  String? iSORGAUTHENTICATIONREQUIRED;
  String? xLSCSVONSEARCHALLOWED;
  String? sUBSCRIPTIONBGCOLOR;
  String? sENDMAILWITHSMS;
  String? dEFAULTDATETIMEFORMAT;
  String? cLIENTTOKENREGEX;
  String? pLAYERREQUIREDFORAPPROVEDWINNING;
  String? wARNAME;
  String? uSERVALIDATIONNOTREQUIREDORGTYPESFORPPL;
  String? aLLOWEDWALLETTYPE;
  String? iNVALIDCHANGEPWDRETRYALLOWED;
  String? pASSWORDREGEX;
  String? iNVOICESYNCREQUIRED;
  String? sERVERIP;
  String? mULTIPLESALEALLOWEDONSAMEGAME;
  String? lOGINWITHOUTTERMINALMAPPING;
  String? uSERNAMEREGEX;
  String? iSZIPCODEMANDATORY;
  String? mAXCOMMISSIONPERCENT;
  String? iSBOGRACEPERIOD;
  String? dEFAULTCREDITLIMIT;
  String? fORCEPASSWORDUPDATE;
  String? oRGDEVICEMAPPING;
  String? SCAN_N_PLAY_ALIAS_NAME;

  Data(
      {this.oTPTYPE,
        this.cOUNTRYCODES,
        this.vERIFYPOSWITHOUTTERMINALMAPPING,
        this.rEPORTCHUNKSIZE,
        this.dEFAULTORGSTATUS,
        this.dIRECTRETAILERDEFAULTSETS,
        this.aSSIGNSCHEDULEDCOMMSET,
        this.mAILBOXPASSWORD,
        this.sYSTEMALLOWEDCHAINTYPECODE,
        this.lENGTHOFDECIMALPLACES,
        this.pLAYERKYCAPPROVALREQUIRED,
        this.dEFAULTDATEFORMAT,
        this.aLLOWLOGINFORBLOCKEDUSER,
        this.oTPLENGTH,
        this.eXTERNALCALLHEADERCREDENTIAL,
        this.rETAILPASSWORDREGEX,
        this.tOKENREGEX,
        this.pASSWORDVALIDITYCHECK,
        this.oRGCODELOGICID,
        this.uSERPERTXNLIMIT,
        this.nEGATIVEDISTRIBUTABLELIMITALLOWED,
        this.wINNINGTAXAPPLICABLE,
        this.dEFAULTTXNIP,
        this.aDDITIONALTRANSACTIONDATA,
        this.mINWINAMOUNTFORPARENTAPPROVAL,
        this.eXPIRYDURATIONFORWRONGPASSWORD,
        this.mAGTDEFAULTSETS,
        this.rETSUBUSERROLEID,
        this.aLLOWEDCHAINTYPE,
        this.mULTIPLEUSERINVENTORYACCESSORGTYPE,
        this.zIPCODEREGEX,
        this.bOUSERSYNCALLOWED,
        this.oLAGAMEID,
        this.cOUNTRYCODE,
        this.aPPDOWNLOADURL,
        this.aWSREGIONVALUE,
        this.cURRENCYID,
        this.cREDITLIMITDISPLAYONAPP,
        this.dATEFORMAT,
        this.uSERPERDAYTXNLIMIT,
        this.sUBUSERALLOWEDORGCODES,
        this.rESCHEDULEALLOWED,
        this.fAILEDLOGINATTEMPT,
        this.tHIRDPARTYUSERSEARCHALLOWED,
        this.sYSTEMID,
        this.oTPEXPIRY,
        this.tDSAPPLICABLE,
        this.pHONEREGEX,
        this.aWSACCESSKEYID,
        this.wEAVERADMINLOGIN,
        this.mOBILEREGEX,
        this.pLAYERTDSRATE,
        this.pLAYERTDSREQUIREDFORNOTAPPROVEDWINNING,
        this.aDVANCEDREGISTRATIONREQUESTSTEPS,
        this.dEFAULTBILLCONFIG,
        this.sHORTCLIENTNAME,
        this.dECIMALCHARACTER,
        this.pASSWORDVALIDITYDAYS,
        this.oRGBANKDETAILSREQUIRED,
        this.dISPLAYCURRENCYSYMBOL,
        this.dEFAULTRETAILERSUBUSERROLE,
        this.uSERDEVICEMAPPING,
        this.rEQUESTTIMESTAMPCHECK,
        this.sUBSCRIPTIONMSGCOLOR,
        this.iSB2BANDB2C,
        this.rMSSERVERURL,
        this.dISPLAYUSERBALANCE,
        this.dAILYTXNSUMMARYNUMBERS,
        this.cONTENTSERVERTYPE,
        this.nUMBERFORMATREQUIRED,
        this.tICKETSERVERIP,
        this.pLAYERREQUIREDFORNOTAPPROVEDWINNING,
        this.rEPORTMAILS,
        this.dEFAULTINVOICESTATUS,
        this.mINWINAMOUNTFORAPPROVAL,
        this.iPCHECKFORCLIENTTOKEN,
        this.aGTSUBUSERROLEID,
        this.bALANCECHECKFORPAYOUT,
        this.oRGCODEREQUIREDONREG,
        this.iSMAILMANDATORY,
        this.rEQUESTTIMEOUT,
        this.aLLOWLOGINFOREXTERNALUSER,
        this.mASTERWAREHOUSEID,
        this.aMOUNTLOCALEFORMATINGREQUIRED,
        this.rEGISTRATIONALLOWEDORGTYPE,
        this.uSERCHECKFORTERMINAL,
        this.tHIRDPARTYUSERUPDATEALLOWED,
        this.uSEMOBILEASUSERNAME,
        this.aWSSECRETACCESSKEY,
        this.dECIMALFORMATINGREQUIRED,
        this.rESOURCEDOWNLOADURL,
        this.rEGISTRATIONREQUESTEXPIRY,
        this.sEARCHLATESTRECORDFIRST,
        this.oRGBANKDETAILSMANDATORY,
        this.tERMINALLOCATIONDETAILS,
        this.aWSSENDERID,
        this.sUBSCRIPTIONMSG,
        this.sMSONPAYMENT,
        this.aLLOWEDWALLETMODE,
        this.lANGUAGECODE,
        this.mAXTXNVALUEALLOWED,
        this.cLIENTDOMAINNAME,
        this.eMAILUNIQUENESS,
        this.cOUNTRY,
        this.nETAMOUNTCHECK,
        this.cURRENCYLIST,
        this.sETTLEMENTBLOCKEDDURATION,
        this.aLERTNUMBERS,
        this.mULTIPLEWAREHOUSEALLOWED,
        this.bOSHUTDOWN,
        this.dEFAULTDOMAINID,
        this.oRGCODEREGEX,
        this.sENDIAMROLEMAIL,
        this.cLAUTOAPPROVALLIMIT,
        this.iSLSENABLED,
        this.oLANETCOLLECTIONCOMMALLOWED,
        this.aLLOWEDORGCODES,
        this.mOBILECODEMINMAXLENGTH,
        this.sYSTEMALLOWEDLANGUAGES,
        this.eNABLEORGPOSASSIGNMENTONREG,
        this.dUPLICATETXNTIMECHECK,
        this.sECONDARYDBSYNC,
        this.mAXCREDITLIMIT,
        this.tHIRDPARTYUSERREQUIRED,
        this.mAILBOXUSERNAME,
        this.uPDATEUSEREMAILWHENORGUPDATE,
        this.domainId,
        this.iPCHECKFORUSERTOKEN,
        this.tDSRATE,
        this.pASSWORDTYPE,
        this.mAXBULKPAYMENTALLOWED,
        this.eNABLEPAYINORGSEARCH,
        this.mAGTSUBUSERROLEID,
        this.bETGAMESID,
        this.lOWERTIERACCESSALLOWED,
        this.domainName,
        this.cLINETTOKENGENERATIONALLOWED,
        this.rEPORTDOWNLOADURL,
        this.iSBACKENDGRACEPERIOD,
        this.mOBILEUNIQUENESS,
        this.oRGTERMINATEDAYS,
        this.sENDIAMROLESMS,
        this.rOUNDOFFREQUIRED,
        this.cLIENTNAME,
        this.lOWERTIERUSERACCESSALLOWED,
        this.mAILBOXEMAILID,
        this.eMAILREGEX,
        this.cALLUSMESSAGE,
        this.aLLOWEDDECIMALSIZE,
        this.sCRIPTUSERID,
        this.pLAYERTDSREQUIREDFORAPPROVEDWINNING,
        this.lOGLOGINACTIVITY,
        this.iSORGMOVEMENT,
        this.dOMAINUSERROLEID,
        this.iSORGAUTHENTICATIONREQUIRED,
        this.xLSCSVONSEARCHALLOWED,
        this.sUBSCRIPTIONBGCOLOR,
        this.sENDMAILWITHSMS,
        this.dEFAULTDATETIMEFORMAT,
        this.cLIENTTOKENREGEX,
        this.pLAYERREQUIREDFORAPPROVEDWINNING,
        this.wARNAME,
        this.uSERVALIDATIONNOTREQUIREDORGTYPESFORPPL,
        this.aLLOWEDWALLETTYPE,
        this.iNVALIDCHANGEPWDRETRYALLOWED,
        this.pASSWORDREGEX,
        this.iNVOICESYNCREQUIRED,
        this.sERVERIP,
        this.mULTIPLESALEALLOWEDONSAMEGAME,
        this.lOGINWITHOUTTERMINALMAPPING,
        this.uSERNAMEREGEX,
        this.iSZIPCODEMANDATORY,
        this.mAXCOMMISSIONPERCENT,
        this.iSBOGRACEPERIOD,
        this.dEFAULTCREDITLIMIT,
        this.fORCEPASSWORDUPDATE,
        this.oRGDEVICEMAPPING,
        this.SCAN_N_PLAY_ALIAS_NAME,
      });

  Data.fromJson(Map<String, dynamic> json) {
    oTPTYPE = json['OTP_TYPE'];
    cOUNTRYCODES = json['COUNTRY_CODES'];
    vERIFYPOSWITHOUTTERMINALMAPPING =
    json['VERIFY_POS_WITHOUT_TERMINAL_MAPPING'];
    rEPORTCHUNKSIZE = json['REPORT_CHUNK_SIZE'];
    dEFAULTORGSTATUS = json['DEFAULT_ORG_STATUS'];
    dIRECTRETAILERDEFAULTSETS = json['DIRECT_RETAILER_DEFAULT_SETS'];
    aSSIGNSCHEDULEDCOMMSET = json['ASSIGN_SCHEDULED_COMM_SET'];
    mAILBOXPASSWORD = json['MAILBOX_PASSWORD'];
    sYSTEMALLOWEDCHAINTYPECODE = json['SYSTEM_ALLOWED_CHAINTYPE_CODE'];
    lENGTHOFDECIMALPLACES = json['LENGTH_OF_DECIMAL_PLACES'];
    pLAYERKYCAPPROVALREQUIRED = json['PLAYER_KYC_APPROVAL_REQUIRED'];
    dEFAULTDATEFORMAT = json['DEFAULT_DATE_FORMAT'];
    aLLOWLOGINFORBLOCKEDUSER = json['ALLOW_LOGIN_FOR_BLOCKED_USER'];
    oTPLENGTH = json['OTP_LENGTH'];
    eXTERNALCALLHEADERCREDENTIAL = json['EXTERNAL_CALL_HEADER_CREDENTIAL'];
    rETAILPASSWORDREGEX = json['RETAIL_PASSWORD_REGEX'];
    tOKENREGEX = json['TOKEN_REGEX'];
    pASSWORDVALIDITYCHECK = json['PASSWORD_VALIDITY_CHECK'];
    oRGCODELOGICID = json['ORG_CODE_LOGIC_ID'];
    uSERPERTXNLIMIT = json['USER_PER_TXN_LIMIT'];
    nEGATIVEDISTRIBUTABLELIMITALLOWED =
    json['NEGATIVE_DISTRIBUTABLE_LIMIT_ALLOWED'];
    wINNINGTAXAPPLICABLE = json['WINNING_TAX_APPLICABLE'];
    dEFAULTTXNIP = json['DEFAULT_TXN_IP'];
    aDDITIONALTRANSACTIONDATA = json['ADDITIONAL_TRANSACTION_DATA'];
    mINWINAMOUNTFORPARENTAPPROVAL = json['MIN_WIN_AMOUNT_FOR_PARENT_APPROVAL'];
    eXPIRYDURATIONFORWRONGPASSWORD = json['EXPIRY_DURATION_FOR_WRONG_PASSWORD'];
    mAGTDEFAULTSETS = json['MAGT_DEFAULT_SETS'];
    rETSUBUSERROLEID = json['RET_SUB_USER_ROLE_ID'];
    aLLOWEDCHAINTYPE = json['ALLOWED_CHAIN_TYPE'];
    mULTIPLEUSERINVENTORYACCESSORGTYPE =
    json['MULTIPLE_USER_INVENTORY_ACCESS_ORG_TYPE'];
    zIPCODEREGEX = json['ZIPCODE_REGEX'];
    bOUSERSYNCALLOWED = json['BO_USER_SYNC_ALLOWED'];
    oLAGAMEID = json['OLA_GAME_ID'];
    cOUNTRYCODE = json['COUNTRY_CODE'];
    aPPDOWNLOADURL = json['APP_DOWNLOAD_URL'];
    aWSREGIONVALUE = json['AWS_REGION_VALUE'];
    cURRENCYID = json['CURRENCY_ID'];
    cREDITLIMITDISPLAYONAPP = json['CREDIT_LIMIT_DISPLAY_ON_APP'];
    dATEFORMAT = json['DATE_FORMAT'];
    uSERPERDAYTXNLIMIT = json['USER_PER_DAY_TXN_LIMIT'];
    sUBUSERALLOWEDORGCODES = json['SUB_USER_ALLOWED_ORG_CODES'];
    rESCHEDULEALLOWED = json['RESCHEDULE_ALLOWED'];
    fAILEDLOGINATTEMPT = json['FAILED_LOGIN_ATTEMPT'];
    tHIRDPARTYUSERSEARCHALLOWED = json['THIRDPARTY_USER_SEARCH_ALLOWED'];
    sYSTEMID = json['SYSTEM_ID'];
    oTPEXPIRY = json['OTP_EXPIRY'];
    tDSAPPLICABLE = json['TDS_APPLICABLE'];
    pHONEREGEX = json['PHONE_REGEX'];
    aWSACCESSKEYID = json['AWS_ACCESS_KEY_ID'];
    wEAVERADMINLOGIN = json['WEAVER_ADMIN_LOGIN'];
    mOBILEREGEX = json['MOBILE_REGEX'];
    pLAYERTDSRATE = json['PLAYER_TDS_RATE'];
    pLAYERTDSREQUIREDFORNOTAPPROVEDWINNING =
    json['PLAYER_TDS_REQUIRED_FOR_NOT_APPROVED_WINNING'];
    aDVANCEDREGISTRATIONREQUESTSTEPS =
    json['ADVANCED_REGISTRATION_REQUEST_STEPS'];
    dEFAULTBILLCONFIG = json['DEFAULT_BILL_CONFIG'];
    sHORTCLIENTNAME = json['SHORT_CLIENT_NAME'];
    dECIMALCHARACTER = json['DECIMAL_CHARACTER'];
    pASSWORDVALIDITYDAYS = json['PASSWORD_VALIDITY_DAYS'];
    oRGBANKDETAILSREQUIRED = json['ORG_BANK_DETAILS_REQUIRED'];
    dISPLAYCURRENCYSYMBOL = json['DISPLAY_CURRENCY_SYMBOL'];
    dEFAULTRETAILERSUBUSERROLE = json['DEFAULT_RETAILER_SUBUSER_ROLE'];
    uSERDEVICEMAPPING = json['USER_DEVICE_MAPPING'];
    rEQUESTTIMESTAMPCHECK = json['REQUEST_TIMESTAMP_CHECK'];
    sUBSCRIPTIONMSGCOLOR = json['SUBSCRIPTION_MSG_COLOR'];
    iSB2BANDB2C = json['IS_B2B_AND_B2C'];
    rMSSERVERURL = json['RMS_SERVER_URL'];
    dISPLAYUSERBALANCE = json['DISPLAY_USER_BALANCE'];
    dAILYTXNSUMMARYNUMBERS = json['DAILY_TXN_SUMMARY_NUMBERS'];
    cONTENTSERVERTYPE = json['CONTENT_SERVER_TYPE'];
    nUMBERFORMATREQUIRED = json['NUMBER_FORMAT_REQUIRED'];
    tICKETSERVERIP = json['TICKET_SERVER_IP'];
    pLAYERREQUIREDFORNOTAPPROVEDWINNING =
    json['PLAYER_REQUIRED_FOR_NOT_APPROVED_WINNING'];
    rEPORTMAILS = json['REPORT_MAILS'];
    dEFAULTINVOICESTATUS = json['DEFAULT_INVOICE_STATUS'];
    mINWINAMOUNTFORAPPROVAL = json['MIN_WIN_AMOUNT_FOR_APPROVAL'];
    iPCHECKFORCLIENTTOKEN = json['IP_CHECK_FOR_CLIENT_TOKEN'];
    aGTSUBUSERROLEID = json['AGT_SUB_USER_ROLE_ID'];
    bALANCECHECKFORPAYOUT = json['BALANCE_CHECK_FOR_PAYOUT'];
    oRGCODEREQUIREDONREG = json['ORGCODE_REQUIRED_ON_REG'];
    iSMAILMANDATORY = json['IS_MAIL_MANDATORY'];
    rEQUESTTIMEOUT = json['REQUEST_TIME_OUT'];
    aLLOWLOGINFOREXTERNALUSER = json['ALLOW_LOGIN_FOR_EXTERNAL_USER'];
    mASTERWAREHOUSEID = json['MASTER_WAREHOUSE_ID'];
    aMOUNTLOCALEFORMATINGREQUIRED = json['AMOUNT_LOCALE_FORMATING_REQUIRED'];
    rEGISTRATIONALLOWEDORGTYPE = json['REGISTRATION_ALLOWED_ORG_TYPE'];
    uSERCHECKFORTERMINAL = json['USER_CHECK_FOR_TERMINAL'];
    tHIRDPARTYUSERUPDATEALLOWED = json['THIRDPARTY_USER_UPDATE_ALLOWED'];
    uSEMOBILEASUSERNAME = json['USE_MOBILE_AS_USERNAME'];
    aWSSECRETACCESSKEY = json['AWS_SECRET_ACCESS_KEY'];
    dECIMALFORMATINGREQUIRED = json['DECIMAL_FORMATING_REQUIRED'];
    rESOURCEDOWNLOADURL = json['RESOURCE_DOWNLOAD_URL'];
    rEGISTRATIONREQUESTEXPIRY = json['REGISTRATION_REQUEST_EXPIRY'];
    sEARCHLATESTRECORDFIRST = json['SEARCH_LATEST_RECORD_FIRST'];
    oRGBANKDETAILSMANDATORY = json['ORG_BANK_DETAILS_MANDATORY'];
    tERMINALLOCATIONDETAILS = json['TERMINAL_LOCATION_DETAILS'];
    aWSSENDERID = json['AWS_SENDER_ID'];
    sUBSCRIPTIONMSG = json['SUBSCRIPTION_MSG'];
    sMSONPAYMENT = json['SMS_ON_PAYMENT'];
    aLLOWEDWALLETMODE = json['ALLOWED_WALLET_MODE'];
    lANGUAGECODE = json['LANGUAGE_CODE'];
    mAXTXNVALUEALLOWED = json['MAX_TXN_VALUE_ALLOWED'];
    cLIENTDOMAINNAME = json['CLIENT_DOMAIN_NAME'];
    eMAILUNIQUENESS = json['EMAIL_UNIQUENESS'];
    cOUNTRY = json['COUNTRY'];
    nETAMOUNTCHECK = json['NET_AMOUNT_CHECK'];
    cURRENCYLIST = json['CURRENCY_LIST'];
    sETTLEMENTBLOCKEDDURATION = json['SETTLEMENT_BLOCKED_DURATION'];
    aLERTNUMBERS = json['ALERT_NUMBERS'];
    mULTIPLEWAREHOUSEALLOWED = json['MULTIPLE_WAREHOUSE_ALLOWED'];
    bOSHUTDOWN = json['BO_SHUTDOWN'];
    dEFAULTDOMAINID = json['DEFAULT_DOMAIN_ID'];
    oRGCODEREGEX = json['ORGCODE_REGEX'];
    sENDIAMROLEMAIL = json['SEND_IAM_ROLE_MAIL'];
    cLAUTOAPPROVALLIMIT = json['CL_AUTO_APPROVAL_LIMIT'];
    iSLSENABLED = json['IS_LS_ENABLED'];
    oLANETCOLLECTIONCOMMALLOWED = json['OLA_NET_COLLECTION_COMM_ALLOWED'];
    aLLOWEDORGCODES = json['ALLOWED_ORG_CODES'];
    mOBILECODEMINMAXLENGTH = json['MOBILE_CODE_MIN_MAX_LENGTH'];
    sYSTEMALLOWEDLANGUAGES = json['SYSTEM_ALLOWED_LANGUAGES'];
    eNABLEORGPOSASSIGNMENTONREG = json['ENABLE_ORG_POS_ASSIGNMENT_ON_REG'];
    dUPLICATETXNTIMECHECK = json['DUPLICATE_TXN_TIME_CHECK'];
    sECONDARYDBSYNC = json['SECONDARY_DB_SYNC'];
    mAXCREDITLIMIT = json['MAX_CREDIT_LIMIT'];
    tHIRDPARTYUSERREQUIRED = json['THIRDPARTY_USER_REQUIRED'];
    mAILBOXUSERNAME = json['MAILBOX_USERNAME'];
    uPDATEUSEREMAILWHENORGUPDATE = json['UPDATE_USER_EMAIL_WHEN_ORG_UPDATE'];
    domainId = json['domainId'];
    iPCHECKFORUSERTOKEN = json['IP_CHECK_FOR_USER_TOKEN'];
    tDSRATE = json['TDS_RATE'];
    pASSWORDTYPE = json['PASSWORD_TYPE'];
    mAXBULKPAYMENTALLOWED = json['MAX_BULK_PAYMENT_ALLOWED'];
    eNABLEPAYINORGSEARCH = json['ENABLE_PAY_IN_ORG_SEARCH'];
    mAGTSUBUSERROLEID = json['MAGT_SUB_USER_ROLE_ID'];
    bETGAMESID = json['BET_GAMES_ID'];
    lOWERTIERACCESSALLOWED = json['LOWER_TIER_ACCESS_ALLOWED'];
    domainName = json['domainName'];
    cLINETTOKENGENERATIONALLOWED = json['CLINET_TOKEN_GENERATION_ALLOWED'];
    rEPORTDOWNLOADURL = json['REPORT_DOWNLOAD_URL'];
    iSBACKENDGRACEPERIOD = json['IS_BACKEND_GRACE_PERIOD'];
    mOBILEUNIQUENESS = json['MOBILE_UNIQUENESS'];
    oRGTERMINATEDAYS = json['ORG_TERMINATE_DAYS'];
    sENDIAMROLESMS = json['SEND_IAM_ROLE_SMS'];
    rOUNDOFFREQUIRED = json['ROUND_OFF_REQUIRED'];
    cLIENTNAME = json['CLIENT_NAME'];
    lOWERTIERUSERACCESSALLOWED = json['LOWER_TIER_USER_ACCESS_ALLOWED'];
    mAILBOXEMAILID = json['MAILBOX_EMAIL_ID'];
    eMAILREGEX = json['EMAIL_REGEX'];
    cALLUSMESSAGE = json['CALL_US_MESSAGE'];
    aLLOWEDDECIMALSIZE = json['ALLOWED_DECIMAL_SIZE'];
    sCRIPTUSERID = json['SCRIPT_USER_ID'];
    pLAYERTDSREQUIREDFORAPPROVEDWINNING =
    json['PLAYER_TDS_REQUIRED_FOR_APPROVED_WINNING'];
    lOGLOGINACTIVITY = json['LOG_LOGIN_ACTIVITY'];
    iSORGMOVEMENT = json['IS_ORG_MOVEMENT'];
    dOMAINUSERROLEID = json['DOMAIN_USER_ROLE_ID'];
    iSORGAUTHENTICATIONREQUIRED = json['IS_ORG_AUTHENTICATION_REQUIRED'];
    xLSCSVONSEARCHALLOWED = json['XLS_CSV_ON_SEARCH_ALLOWED'];
    sUBSCRIPTIONBGCOLOR = json['SUBSCRIPTION_BG_COLOR'];
    sENDMAILWITHSMS = json['SEND_MAIL_WITH_SMS'];
    dEFAULTDATETIMEFORMAT = json['DEFAULT_DATETIME_FORMAT'];
    cLIENTTOKENREGEX = json['CLIENT_TOKEN_REGEX'];
    pLAYERREQUIREDFORAPPROVEDWINNING =
    json['PLAYER_REQUIRED_FOR_APPROVED_WINNING'];
    wARNAME = json['WAR_NAME'];
    uSERVALIDATIONNOTREQUIREDORGTYPESFORPPL =
    json['USER_VALIDATION_NOT_REQUIRED_ORG_TYPES_FOR_PPL'];
    aLLOWEDWALLETTYPE = json['ALLOWED_WALLET_TYPE'];
    iNVALIDCHANGEPWDRETRYALLOWED = json['INVALID_CHANGE_PWD_RETRY_ALLOWED'];
    pASSWORDREGEX = json['PASSWORD_REGEX'];
    iNVOICESYNCREQUIRED = json['INVOICE_SYNC_REQUIRED'];
    sERVERIP = json['SERVER_IP'];
    mULTIPLESALEALLOWEDONSAMEGAME = json['MULTIPLE_SALE_ALLOWED_ON_SAME_GAME'];
    lOGINWITHOUTTERMINALMAPPING = json['LOGIN_WITHOUT_TERMINAL_MAPPING'];
    uSERNAMEREGEX = json['USERNAME_REGEX'];
    iSZIPCODEMANDATORY = json['IS_ZIPCODE_MANDATORY'];
    mAXCOMMISSIONPERCENT = json['MAX_COMMISSION_PERCENT'];
    iSBOGRACEPERIOD = json['IS_BO_GRACE_PERIOD'];
    dEFAULTCREDITLIMIT = json['DEFAULT_CREDIT_LIMIT'];
    fORCEPASSWORDUPDATE = json['FORCE_PASSWORD_UPDATE'];
    oRGDEVICEMAPPING = json['ORG_DEVICE_MAPPING'];
    SCAN_N_PLAY_ALIAS_NAME = json['SCAN_N_PLAY_ALIAS_NAME'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['OTP_TYPE'] = this.oTPTYPE;
    data['COUNTRY_CODES'] = this.cOUNTRYCODES;
    data['VERIFY_POS_WITHOUT_TERMINAL_MAPPING'] =
        this.vERIFYPOSWITHOUTTERMINALMAPPING;
    data['REPORT_CHUNK_SIZE'] = this.rEPORTCHUNKSIZE;
    data['DEFAULT_ORG_STATUS'] = this.dEFAULTORGSTATUS;
    data['DIRECT_RETAILER_DEFAULT_SETS'] = this.dIRECTRETAILERDEFAULTSETS;
    data['ASSIGN_SCHEDULED_COMM_SET'] = this.aSSIGNSCHEDULEDCOMMSET;
    data['MAILBOX_PASSWORD'] = this.mAILBOXPASSWORD;
    data['SYSTEM_ALLOWED_CHAINTYPE_CODE'] = this.sYSTEMALLOWEDCHAINTYPECODE;
    data['LENGTH_OF_DECIMAL_PLACES'] = this.lENGTHOFDECIMALPLACES;
    data['PLAYER_KYC_APPROVAL_REQUIRED'] = this.pLAYERKYCAPPROVALREQUIRED;
    data['DEFAULT_DATE_FORMAT'] = this.dEFAULTDATEFORMAT;
    data['ALLOW_LOGIN_FOR_BLOCKED_USER'] = this.aLLOWLOGINFORBLOCKEDUSER;
    data['OTP_LENGTH'] = this.oTPLENGTH;
    data['EXTERNAL_CALL_HEADER_CREDENTIAL'] = this.eXTERNALCALLHEADERCREDENTIAL;
    data['RETAIL_PASSWORD_REGEX'] = this.rETAILPASSWORDREGEX;
    data['TOKEN_REGEX'] = this.tOKENREGEX;
    data['PASSWORD_VALIDITY_CHECK'] = this.pASSWORDVALIDITYCHECK;
    data['ORG_CODE_LOGIC_ID'] = this.oRGCODELOGICID;
    data['USER_PER_TXN_LIMIT'] = this.uSERPERTXNLIMIT;
    data['NEGATIVE_DISTRIBUTABLE_LIMIT_ALLOWED'] =
        this.nEGATIVEDISTRIBUTABLELIMITALLOWED;
    data['WINNING_TAX_APPLICABLE'] = this.wINNINGTAXAPPLICABLE;
    data['DEFAULT_TXN_IP'] = this.dEFAULTTXNIP;
    data['ADDITIONAL_TRANSACTION_DATA'] = this.aDDITIONALTRANSACTIONDATA;
    data['MIN_WIN_AMOUNT_FOR_PARENT_APPROVAL'] =
        this.mINWINAMOUNTFORPARENTAPPROVAL;
    data['EXPIRY_DURATION_FOR_WRONG_PASSWORD'] =
        this.eXPIRYDURATIONFORWRONGPASSWORD;
    data['MAGT_DEFAULT_SETS'] = this.mAGTDEFAULTSETS;
    data['RET_SUB_USER_ROLE_ID'] = this.rETSUBUSERROLEID;
    data['ALLOWED_CHAIN_TYPE'] = this.aLLOWEDCHAINTYPE;
    data['MULTIPLE_USER_INVENTORY_ACCESS_ORG_TYPE'] =
        this.mULTIPLEUSERINVENTORYACCESSORGTYPE;
    data['ZIPCODE_REGEX'] = this.zIPCODEREGEX;
    data['BO_USER_SYNC_ALLOWED'] = this.bOUSERSYNCALLOWED;
    data['OLA_GAME_ID'] = this.oLAGAMEID;
    data['COUNTRY_CODE'] = this.cOUNTRYCODE;
    data['APP_DOWNLOAD_URL'] = this.aPPDOWNLOADURL;
    data['AWS_REGION_VALUE'] = this.aWSREGIONVALUE;
    data['CURRENCY_ID'] = this.cURRENCYID;
    data['CREDIT_LIMIT_DISPLAY_ON_APP'] = this.cREDITLIMITDISPLAYONAPP;
    data['DATE_FORMAT'] = this.dATEFORMAT;
    data['USER_PER_DAY_TXN_LIMIT'] = this.uSERPERDAYTXNLIMIT;
    data['SUB_USER_ALLOWED_ORG_CODES'] = this.sUBUSERALLOWEDORGCODES;
    data['RESCHEDULE_ALLOWED'] = this.rESCHEDULEALLOWED;
    data['FAILED_LOGIN_ATTEMPT'] = this.fAILEDLOGINATTEMPT;
    data['THIRDPARTY_USER_SEARCH_ALLOWED'] = this.tHIRDPARTYUSERSEARCHALLOWED;
    data['SYSTEM_ID'] = this.sYSTEMID;
    data['OTP_EXPIRY'] = this.oTPEXPIRY;
    data['TDS_APPLICABLE'] = this.tDSAPPLICABLE;
    data['PHONE_REGEX'] = this.pHONEREGEX;
    data['AWS_ACCESS_KEY_ID'] = this.aWSACCESSKEYID;
    data['WEAVER_ADMIN_LOGIN'] = this.wEAVERADMINLOGIN;
    data['MOBILE_REGEX'] = this.mOBILEREGEX;
    data['PLAYER_TDS_RATE'] = this.pLAYERTDSRATE;
    data['PLAYER_TDS_REQUIRED_FOR_NOT_APPROVED_WINNING'] =
        this.pLAYERTDSREQUIREDFORNOTAPPROVEDWINNING;
    data['ADVANCED_REGISTRATION_REQUEST_STEPS'] =
        this.aDVANCEDREGISTRATIONREQUESTSTEPS;
    data['DEFAULT_BILL_CONFIG'] = this.dEFAULTBILLCONFIG;
    data['SHORT_CLIENT_NAME'] = this.sHORTCLIENTNAME;
    data['DECIMAL_CHARACTER'] = this.dECIMALCHARACTER;
    data['PASSWORD_VALIDITY_DAYS'] = this.pASSWORDVALIDITYDAYS;
    data['ORG_BANK_DETAILS_REQUIRED'] = this.oRGBANKDETAILSREQUIRED;
    data['DISPLAY_CURRENCY_SYMBOL'] = this.dISPLAYCURRENCYSYMBOL;
    data['DEFAULT_RETAILER_SUBUSER_ROLE'] = this.dEFAULTRETAILERSUBUSERROLE;
    data['USER_DEVICE_MAPPING'] = this.uSERDEVICEMAPPING;
    data['REQUEST_TIMESTAMP_CHECK'] = this.rEQUESTTIMESTAMPCHECK;
    data['SUBSCRIPTION_MSG_COLOR'] = this.sUBSCRIPTIONMSGCOLOR;
    data['IS_B2B_AND_B2C'] = this.iSB2BANDB2C;
    data['RMS_SERVER_URL'] = this.rMSSERVERURL;
    data['DISPLAY_USER_BALANCE'] = this.dISPLAYUSERBALANCE;
    data['DAILY_TXN_SUMMARY_NUMBERS'] = this.dAILYTXNSUMMARYNUMBERS;
    data['CONTENT_SERVER_TYPE'] = this.cONTENTSERVERTYPE;
    data['NUMBER_FORMAT_REQUIRED'] = this.nUMBERFORMATREQUIRED;
    data['TICKET_SERVER_IP'] = this.tICKETSERVERIP;
    data['PLAYER_REQUIRED_FOR_NOT_APPROVED_WINNING'] =
        this.pLAYERREQUIREDFORNOTAPPROVEDWINNING;
    data['REPORT_MAILS'] = this.rEPORTMAILS;
    data['DEFAULT_INVOICE_STATUS'] = this.dEFAULTINVOICESTATUS;
    data['MIN_WIN_AMOUNT_FOR_APPROVAL'] = this.mINWINAMOUNTFORAPPROVAL;
    data['IP_CHECK_FOR_CLIENT_TOKEN'] = this.iPCHECKFORCLIENTTOKEN;
    data['AGT_SUB_USER_ROLE_ID'] = this.aGTSUBUSERROLEID;
    data['BALANCE_CHECK_FOR_PAYOUT'] = this.bALANCECHECKFORPAYOUT;
    data['ORGCODE_REQUIRED_ON_REG'] = this.oRGCODEREQUIREDONREG;
    data['IS_MAIL_MANDATORY'] = this.iSMAILMANDATORY;
    data['REQUEST_TIME_OUT'] = this.rEQUESTTIMEOUT;
    data['ALLOW_LOGIN_FOR_EXTERNAL_USER'] = this.aLLOWLOGINFOREXTERNALUSER;
    data['MASTER_WAREHOUSE_ID'] = this.mASTERWAREHOUSEID;
    data['AMOUNT_LOCALE_FORMATING_REQUIRED'] =
        this.aMOUNTLOCALEFORMATINGREQUIRED;
    data['REGISTRATION_ALLOWED_ORG_TYPE'] = this.rEGISTRATIONALLOWEDORGTYPE;
    data['USER_CHECK_FOR_TERMINAL'] = this.uSERCHECKFORTERMINAL;
    data['THIRDPARTY_USER_UPDATE_ALLOWED'] = this.tHIRDPARTYUSERUPDATEALLOWED;
    data['USE_MOBILE_AS_USERNAME'] = this.uSEMOBILEASUSERNAME;
    data['AWS_SECRET_ACCESS_KEY'] = this.aWSSECRETACCESSKEY;
    data['DECIMAL_FORMATING_REQUIRED'] = this.dECIMALFORMATINGREQUIRED;
    data['RESOURCE_DOWNLOAD_URL'] = this.rESOURCEDOWNLOADURL;
    data['REGISTRATION_REQUEST_EXPIRY'] = this.rEGISTRATIONREQUESTEXPIRY;
    data['SEARCH_LATEST_RECORD_FIRST'] = this.sEARCHLATESTRECORDFIRST;
    data['ORG_BANK_DETAILS_MANDATORY'] = this.oRGBANKDETAILSMANDATORY;
    data['TERMINAL_LOCATION_DETAILS'] = this.tERMINALLOCATIONDETAILS;
    data['AWS_SENDER_ID'] = this.aWSSENDERID;
    data['SUBSCRIPTION_MSG'] = this.sUBSCRIPTIONMSG;
    data['SMS_ON_PAYMENT'] = this.sMSONPAYMENT;
    data['ALLOWED_WALLET_MODE'] = this.aLLOWEDWALLETMODE;
    data['LANGUAGE_CODE'] = this.lANGUAGECODE;
    data['MAX_TXN_VALUE_ALLOWED'] = this.mAXTXNVALUEALLOWED;
    data['CLIENT_DOMAIN_NAME'] = this.cLIENTDOMAINNAME;
    data['EMAIL_UNIQUENESS'] = this.eMAILUNIQUENESS;
    data['COUNTRY'] = this.cOUNTRY;
    data['NET_AMOUNT_CHECK'] = this.nETAMOUNTCHECK;
    data['CURRENCY_LIST'] = this.cURRENCYLIST;
    data['SETTLEMENT_BLOCKED_DURATION'] = this.sETTLEMENTBLOCKEDDURATION;
    data['ALERT_NUMBERS'] = this.aLERTNUMBERS;
    data['MULTIPLE_WAREHOUSE_ALLOWED'] = this.mULTIPLEWAREHOUSEALLOWED;
    data['BO_SHUTDOWN'] = this.bOSHUTDOWN;
    data['DEFAULT_DOMAIN_ID'] = this.dEFAULTDOMAINID;
    data['ORGCODE_REGEX'] = this.oRGCODEREGEX;
    data['SEND_IAM_ROLE_MAIL'] = this.sENDIAMROLEMAIL;
    data['CL_AUTO_APPROVAL_LIMIT'] = this.cLAUTOAPPROVALLIMIT;
    data['IS_LS_ENABLED'] = this.iSLSENABLED;
    data['OLA_NET_COLLECTION_COMM_ALLOWED'] = this.oLANETCOLLECTIONCOMMALLOWED;
    data['ALLOWED_ORG_CODES'] = this.aLLOWEDORGCODES;
    data['MOBILE_CODE_MIN_MAX_LENGTH'] = this.mOBILECODEMINMAXLENGTH;
    data['SYSTEM_ALLOWED_LANGUAGES'] = this.sYSTEMALLOWEDLANGUAGES;
    data['ENABLE_ORG_POS_ASSIGNMENT_ON_REG'] = this.eNABLEORGPOSASSIGNMENTONREG;
    data['DUPLICATE_TXN_TIME_CHECK'] = this.dUPLICATETXNTIMECHECK;
    data['SECONDARY_DB_SYNC'] = this.sECONDARYDBSYNC;
    data['MAX_CREDIT_LIMIT'] = this.mAXCREDITLIMIT;
    data['THIRDPARTY_USER_REQUIRED'] = this.tHIRDPARTYUSERREQUIRED;
    data['MAILBOX_USERNAME'] = this.mAILBOXUSERNAME;
    data['UPDATE_USER_EMAIL_WHEN_ORG_UPDATE'] =
        this.uPDATEUSEREMAILWHENORGUPDATE;
    data['domainId'] = this.domainId;
    data['IP_CHECK_FOR_USER_TOKEN'] = this.iPCHECKFORUSERTOKEN;
    data['TDS_RATE'] = this.tDSRATE;
    data['PASSWORD_TYPE'] = this.pASSWORDTYPE;
    data['MAX_BULK_PAYMENT_ALLOWED'] = this.mAXBULKPAYMENTALLOWED;
    data['ENABLE_PAY_IN_ORG_SEARCH'] = this.eNABLEPAYINORGSEARCH;
    data['MAGT_SUB_USER_ROLE_ID'] = this.mAGTSUBUSERROLEID;
    data['BET_GAMES_ID'] = this.bETGAMESID;
    data['LOWER_TIER_ACCESS_ALLOWED'] = this.lOWERTIERACCESSALLOWED;
    data['domainName'] = this.domainName;
    data['CLINET_TOKEN_GENERATION_ALLOWED'] = this.cLINETTOKENGENERATIONALLOWED;
    data['REPORT_DOWNLOAD_URL'] = this.rEPORTDOWNLOADURL;
    data['IS_BACKEND_GRACE_PERIOD'] = this.iSBACKENDGRACEPERIOD;
    data['MOBILE_UNIQUENESS'] = this.mOBILEUNIQUENESS;
    data['ORG_TERMINATE_DAYS'] = this.oRGTERMINATEDAYS;
    data['SEND_IAM_ROLE_SMS'] = this.sENDIAMROLESMS;
    data['ROUND_OFF_REQUIRED'] = this.rOUNDOFFREQUIRED;
    data['CLIENT_NAME'] = this.cLIENTNAME;
    data['LOWER_TIER_USER_ACCESS_ALLOWED'] = this.lOWERTIERUSERACCESSALLOWED;
    data['MAILBOX_EMAIL_ID'] = this.mAILBOXEMAILID;
    data['EMAIL_REGEX'] = this.eMAILREGEX;
    data['CALL_US_MESSAGE'] = this.cALLUSMESSAGE;
    data['ALLOWED_DECIMAL_SIZE'] = this.aLLOWEDDECIMALSIZE;
    data['SCRIPT_USER_ID'] = this.sCRIPTUSERID;
    data['PLAYER_TDS_REQUIRED_FOR_APPROVED_WINNING'] =
        this.pLAYERTDSREQUIREDFORAPPROVEDWINNING;
    data['LOG_LOGIN_ACTIVITY'] = this.lOGLOGINACTIVITY;
    data['IS_ORG_MOVEMENT'] = this.iSORGMOVEMENT;
    data['DOMAIN_USER_ROLE_ID'] = this.dOMAINUSERROLEID;
    data['IS_ORG_AUTHENTICATION_REQUIRED'] = this.iSORGAUTHENTICATIONREQUIRED;
    data['XLS_CSV_ON_SEARCH_ALLOWED'] = this.xLSCSVONSEARCHALLOWED;
    data['SUBSCRIPTION_BG_COLOR'] = this.sUBSCRIPTIONBGCOLOR;
    data['SEND_MAIL_WITH_SMS'] = this.sENDMAILWITHSMS;
    data['DEFAULT_DATETIME_FORMAT'] = this.dEFAULTDATETIMEFORMAT;
    data['CLIENT_TOKEN_REGEX'] = this.cLIENTTOKENREGEX;
    data['PLAYER_REQUIRED_FOR_APPROVED_WINNING'] =
        this.pLAYERREQUIREDFORAPPROVEDWINNING;
    data['WAR_NAME'] = this.wARNAME;
    data['USER_VALIDATION_NOT_REQUIRED_ORG_TYPES_FOR_PPL'] =
        this.uSERVALIDATIONNOTREQUIREDORGTYPESFORPPL;
    data['ALLOWED_WALLET_TYPE'] = this.aLLOWEDWALLETTYPE;
    data['INVALID_CHANGE_PWD_RETRY_ALLOWED'] =
        this.iNVALIDCHANGEPWDRETRYALLOWED;
    data['PASSWORD_REGEX'] = this.pASSWORDREGEX;
    data['INVOICE_SYNC_REQUIRED'] = this.iNVOICESYNCREQUIRED;
    data['SERVER_IP'] = this.sERVERIP;
    data['MULTIPLE_SALE_ALLOWED_ON_SAME_GAME'] =
        this.mULTIPLESALEALLOWEDONSAMEGAME;
    data['LOGIN_WITHOUT_TERMINAL_MAPPING'] = this.lOGINWITHOUTTERMINALMAPPING;
    data['USERNAME_REGEX'] = this.uSERNAMEREGEX;
    data['IS_ZIPCODE_MANDATORY'] = this.iSZIPCODEMANDATORY;
    data['MAX_COMMISSION_PERCENT'] = this.mAXCOMMISSIONPERCENT;
    data['IS_BO_GRACE_PERIOD'] = this.iSBOGRACEPERIOD;
    data['DEFAULT_CREDIT_LIMIT'] = this.dEFAULTCREDITLIMIT;
    data['FORCE_PASSWORD_UPDATE'] = this.fORCEPASSWORDUPDATE;
    data['ORG_DEVICE_MAPPING'] = this.oRGDEVICEMAPPING;
    data['SCAN_N_PLAY_ALIAS_NAME'] = this.SCAN_N_PLAY_ALIAS_NAME;
    return data;
  }
}
